
num1 = 0
list_of_numbers = []
while num1 <= 9:
    num2 = 0
    while num2 <= 9:
        num3 = 0
        while num3 <= 9:
            num4 = 0
            while num4 <= 9:
                num5 = 0
                while num5 <= 9:
                    num6 = 0
                    while num6 <= 9:
                        num7 = 0
                        while num7 <= 9:
                            num8 = 0
                            while num8 <= 9:
                                num9 = 0
                                while num9 <= 9:
                                    num10 = 0
                                    while num10 <= 9:
                                        num11 = 0
                                        while num11 <= 9:
                                            num12 = 0
                                            while num12 <= 9:
                                                num13 = 0
                                                while num13 <= 9:
                                                    num14 = 0
                                                    while num14 <= 9:
                                                        num15 = 0
                                                        while num15 <= 9:
                                                            num16 = 0
                                                            while num16 <= 9:
                                                                num17 = 0
                                                                while num17 <= 9:
                                                                    num18 = 0
                                                                    while num18 <= 9:
                                                                        num19 = 0
                                                                        while num19 <= 9:
                                                                            num20 = 0
                                                                            while num20 <= 9:
                                                                                num21 = 0
                                                                                while num21 <= 9:
                                                                                     list_of_numbers.append([num1, num2, num3, num4, num5, num6, num7, num8, num9, num10, num11, num12, num13, num14, num15, num16, num17, num18, num19, num20, num21])
                                                                                     num21 += 1
                                                                                num20 += 1
                                                                            num19 += 1
                                                                        num18 += 1
                                                                    num17 += 1
                                                                num16 += 1
                                                            num15 += 1
                                                        num14 += 1
                                                    num13 += 1
                                                num12 += 1
                                            num11 += 1
                                        num10 += 1
                                    num9 += 1
                                num8 += 1
                            num7 += 1
                        num6 += 1
                    num5 += 1
                num4 += 1
            num3 += 1
        num2 += 1
    num1 += 1
    print(list_of_numbers)