print('You are driving a bus')
print('There are 5 people on the bus')
print('3 people get on')
print('How many people are on the bus?')
Ansr = int(input())
print('2 people get off')
print('How many people are on the bus?')
Ansr = int(input())
print('4 people get off')
print('How many people are on the bus?')
Ansr = int(input())
print('5 people get on')
print('How many people are on the bus?')
Ansr = int(input())
print('4 people get on')
print('How many people are on the bus?')
Ansr = int(input())
print('According to you there are', Ansr, 'people on the bus currently')
print('What is the name of the bus driver?')
rdlAnsr = input()
print('I said YOU are driving a bus')
print('you said the bus driver is', rdlAnsr)
